# Generated by Django 5.0.2 on 2024-02-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cart_cartitems'),
        ('products', '0005_product_size_variant_alter_product_color_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_cart', to='products.product'),
        ),
    ]
