# Generated by Django 5.0.2 on 2024-02-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_cartitems_product'),
        ('products', '0006_alter_colorvariant_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='color_variant',
            field=models.ForeignKey(blank=True, default='BLUE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.colorvariant'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='size_variant',
            field=models.ForeignKey(blank=True, default='S', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.sizevariant'),
        ),
    ]
