# Generated by Django 5.0.2 on 2024-02-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_cartitems_color_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
