# Generated by Django 5.0.2 on 2024-02-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_size_variant_alter_product_color_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='color_name',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='size_name',
            field=models.CharField(default='S', max_length=100),
        ),
    ]
